"""Поиск аномальных GMV-сегментов."""

from .anomaly_scoring import (
    apply_hierarchy_score_adjustment,
    build_anomaly_candidates,
    build_atomic_coverage,
    build_ratio_anomaly_candidates,
    calculate_exact_ratio_contribution,
    calculate_segment_anomaly,
    calculate_ratio_segment_anomaly,
    validate_hierarchy_reconciliation,
)
from .config import (
    CURRENT_CAL_DATE,
    DIM_COLUMNS,
    INPUT_PATH,
    OUTPUT_PATH,
    PERIOD,
    RATIO_METRICS,
    RATIO_TREE_OUTPUT_PATH,
    RATIO_TREES_OUTPUT_DIR,
    SHEET_NAME,
    THRESHOLDS,
    TREE_OUTPUT_PATH,
    AnomalyThresholds,
    PILOT_RATIO_METRICS,
    RatioMetricSpec,
)
from .data_preparation import (
    build_full_week_grid,
    build_segment_key_and_level,
    candidate_covers_atomic,
    infer_anomaly_dimension_columns,
    load_history_table,
    normalize_dim_value,
    period_to_weeks,
    prepare_history_dataframe,
    segment_id_from_row,
)
from .pipeline import run_anomaly_analysis, run_pipeline
from .reporting import (
    build_anomaly_analysis_sheet,
    build_anomaly_tree_from_excel,
    build_control_table,
    build_history_for_selected,
    build_manager_summary,
    build_missing_zero_report,
    build_ratio_analysis_sheets,
    highlight_manager_rows_on_anomaly_analysis,
    write_anomaly_excel,
)
from .set_packing import search_anomal, validate_set_packing_solution

# [ADDED] Трендовый MVP экспортируется отдельно и не участвует в anomaly pipeline.
from .trend_analysis import (
    DECLINE,
    GROWTH,
    NO_DIRECTION,
    LinearModelFit,
    SegmentTrendAnalysis,
    TrendChangeEvaluation,
    TrendEvaluation,
    TrendModelConfig,
    TrendThresholds,
    TrendWindowEvaluation,
    analyze_segment_trend,
    build_configured_trend_analysis,
    build_trend_analysis,
    evaluate_change_candidates,
    evaluate_suffix_trends,
    evaluate_trend,
    fit_continuous_piecewise_model,
    fit_single_linear_model,
    select_change_point,
    theil_sen_slope,
    trim_leading_zero_history,
)
from .trend_most_recent_cp import build_most_recent_cp_trend_analysis
# ADDED: Компактная витрина трендов для Excel, YT и DataLens.
from .trend_manager_output import build_manager_trend_output
# ADDED: Trend scoring запускается только после завершения поиска трендов.
from .trend_scoring import (
    TrendScoringConfig,
    apply_trend_hierarchy_adjustment,
    build_trend_selection,
    calculate_own_trend_scores,
)

__all__ = [
    "AnomalyThresholds",
    "DECLINE",
    "GROWTH",
    "NO_DIRECTION",
    "LinearModelFit",
    "RatioMetricSpec",
    "SegmentTrendAnalysis",
    "TrendChangeEvaluation",
    "TrendEvaluation",
    "TrendModelConfig",
    "TrendScoringConfig",
    "TrendThresholds",
    "TrendWindowEvaluation",
    "PILOT_RATIO_METRICS",
    "RATIO_METRICS",
    "CURRENT_CAL_DATE",
    "DIM_COLUMNS",
    "INPUT_PATH",
    "OUTPUT_PATH",
    "PERIOD",
    "RATIO_TREE_OUTPUT_PATH",
    "RATIO_TREES_OUTPUT_DIR",
    "SHEET_NAME",
    "THRESHOLDS",
    "TREE_OUTPUT_PATH",
    "apply_hierarchy_score_adjustment",
    "apply_trend_hierarchy_adjustment",
    "analyze_segment_trend",
    "build_anomaly_analysis_sheet",
    "build_anomaly_candidates",
    "build_anomaly_tree_from_excel",
    "build_atomic_coverage",
    "build_ratio_anomaly_candidates",
    "build_ratio_analysis_sheets",
    "build_control_table",
    "build_full_week_grid",
    "build_configured_trend_analysis",
    "build_history_for_selected",
    "build_manager_summary",
    "build_manager_trend_output",
    "build_missing_zero_report",
    "build_segment_key_and_level",
    "build_trend_analysis",
    "build_trend_selection",
    "build_most_recent_cp_trend_analysis",
    "calculate_segment_anomaly",
    "calculate_own_trend_scores",
    "calculate_exact_ratio_contribution",
    "calculate_ratio_segment_anomaly",
    "candidate_covers_atomic",
    "highlight_manager_rows_on_anomaly_analysis",
    "infer_anomaly_dimension_columns",
    "load_history_table",
    "normalize_dim_value",
    "period_to_weeks",
    "prepare_history_dataframe",
    "evaluate_change_candidates",
    "evaluate_suffix_trends",
    "evaluate_trend",
    "fit_continuous_piecewise_model",
    "fit_single_linear_model",
    "run_anomaly_analysis",
    "run_pipeline",
    "search_anomal",
    "select_change_point",
    "segment_id_from_row",
    "theil_sen_slope",
    "trim_leading_zero_history",
    "validate_set_packing_solution",
    "validate_hierarchy_reconciliation",
    "write_anomaly_excel",
]
